### ISSUE TITLE
Can you add support for OPTIONS (Video Quality)? #enhancements

### ISSUE THREAD

**Issue by abdulmominsakib** [OzakIOne/termux-youtube-dl#1]
If there is an option and I don't know please let me know about it. Currently, this is downloading a slightly low-quality video than I expected.

**Comment by OzakIOne** [comment]
Could you give me the URL where it doesn't download the best quality available ?
I'll look into putting a menu to choose video or audio quality because for now there is no such things.

**Comment by abdulmominsakib** [comment]
Okay... These are the videos I am trying to download in high quality. It would be helpful if you can add a video quality chooser. And you can make a default choice button also. Just suggesting.

https://youtu.be/frGkE231PFs

**Comment by OzakIOne** [comment]
@abdulmominsakib 
Hello, you can now choose video & audio quality for youtube videos
Make sure to do : `rm -f ~/bin/termux-url-opener ~/.config/youtube-dl/config` before installing the new script
