### ISSUE TITLE
Error says following file does not exist

### ISSUE THREAD

**Issue by waleed094** [OzakIOne/termux-youtube-dl#5]
$home/bin/termux-url-opener

**Comment by drowhunter** [comment]
What was the solution to this as I just got the same error?

**Comment by OzakIOne** [comment]
> What was the solution to this as I just got the same error?

Do you have downloaded termux from f droid and not playstore ?

**Comment by drowhunter** [comment]
Yes, from fdroid.  I managed to get it working by downloading the termux-url-opener manually from [here](https://gist.github.com/LordH3lmchen/dc35e8df3dc41d126683f18fe44ebe17) , following the instructions in the comments of the file.
