### ISSUE TITLE
Change yt-dlp configuration directory

### ISSUE THREAD

**Issue by suiljex** [OzakIOne/termux-youtube-dl#6]
yt-dlp tries to load user configuration from `%XDG_CONFIG_HOME%/yt-dlp/config` where `%XDG_CONFIG_HOME%` defaults to `~/.config` if undefined
https://github.com/OzakIOne/termux-youtube-dl/blob/1b709749b654bf652e006bd27265ccbd398dccc6/install.sh#L8
Should be `YOUTUBEDL_CONFIG_FOLDER="${WORKING_DIR}/.config/yt-dlp/"`

**Comment by OzakIOne** [comment]
Thanks for the info, I'll push a fix for it
