### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by PARKasd** [OzakIOne/termux-youtube-dl#7]
![Screenshot_20211214-204354_Termux](https://user-images.githubusercontent.com/66772247/146004811-3b07810c-cc98-43c4-9221-7a9b64a3ac6f.png)

Error shown in termux

**Comment by OzakIOne** [comment]
Have you tried uninstalling and installing again termux ? I've never encoutered this issue I can't help you that much :/

**Comment by agasthya36** [comment]
Install termux app from F- droid and do "pkg update".
You should be good to go.

**Comment by PARKasd** [comment]
solved. use 0.118
